### PR TITLE
fix updated hsc output

### LINKED ISSUE #55: source-update/update-rat.sh does not work
Greetings,
because of format change at https://covid-19-diagnostics.jrc.ec.europa.eu/devices/hsc-common-recognition-rat this script no longer works. I have no clue if that format change is permanent but:
- we lost the `.extracted_on` property
- and all manufacturers/devices are directly listed under root (`.device_list[]` -> `.[]`)

### PR DESCRIPTION
**Pull request by danka74**
I have made a patch to the script using "now" (i.e. current date/time). Fixes #55 

<s>I don't remember the exact format of the date in previous version though...</s>

Fixed date format!

### CODE REVIEW

**Review by dslmeinte — COMMENTED** [review]
Two questions/remarks:

- This change causes the `version` field of every entry to be `null`. Is that intended?
- Would it be possible to sort this list by ID? That makes it quite a bit easier to compare version tracked over time.

**Comment by danka74** [comment]
No, "verison": null is not intended, there seem to be more changes the the JRC format. The script used to rely on hsc_list_history which is now generally not populated.

**Comment by skounis** [comment]
@dslmeinte We need to pay attention to this. Is this script still used, or is it deprecated? We have already moved this responsibility to the Gateway, and the value sets are created and distributed from there. 

Should we keep maintaining this script here as well?

**Comment by dslmeinte** [comment]
> No, "verison": null is not intended, there seem to be more changes the the JRC format. The script used to rely on hsc_list_history which is now generally not populated.

Hmmm, I wonder how TSi do their updates then, because in the end they update this list on the EU DCC Gateway, but I'm not sure which script they use for that. (It's likely they've got their own, and are not feeding that back.)

**Comment by danka74** [comment]
Ok, so if this script is deprecated then maybe that should be stated in the file?

**Comment by dslmeinte** [comment]
> @dslmeinte We need to pay attention to this. Is this script still used, or is it deprecated? We have already moved this responsibility to the Gateway, and the value sets are created and distributed from there.
> 
> Should we keep maintaining this script here as well?

I think it'd be good to know _how exactly_ TSi update that value set, if only in the interest of being able to “keep the lights on”.

**Comment by skounis** [comment]
For the extraction of the values and the creation of the value sets, the Gateway uses the following:
- https://github.com/eu-digital-green-certificates/dgc-gateway/blob/main/src/main/java/eu/europa/ec/dgc/gateway/service/RatValuesetUpdateService.java

Since we do that there, I would suggest marking anything related to JRC/RAT as deprecated in this repository.

**Comment by danka74** [comment]
ok, I will close this PR and create a new one with a deprecation statement.
/Daniel

**Comment by dslmeinte** [comment]
> For the extraction of the values and the creation of the value sets, the Gateway uses the following:
> 
>     * https://github.com/eu-digital-green-certificates/dgc-gateway/blob/main/src/main/java/eu/europa/ec/dgc/gateway/service/RatValuesetUpdateService.java
> 
> 
> Since we do that there, I would suggest marking anything related to JRC/RAT as deprecated in this repository.

Agree. In which case there's not really a point in updating the script in our repository.

We should also include an explanation of the process and that link.

**Comment by mirehak** [comment]
Hi there. 
The class `RatValuesetUpdateService.java` seems to be doing the same job as the script `source-update/update-rat.sh` did. I guess there will be the same issue with the source json format change. At test-dgcg the exposed data (https://test-dgcg-ws.tech.ec.europa.eu/valuesets/covid-19-lab-test-manufacturer-and-name) was updated at 2021-07-01. Is there any more up-to-date valueset available? It is supposed to be scheduled every 6 hours, right?

**Pull request closed without merging**
