### PR TITLE
Update value sets for guidelines document v1.11 (to be adopted)

### PR DESCRIPTION
**Pull request by dslmeinte**

### CODE REVIEW

**Review by danka74 — APPROVED** [review]
The v1.11 document has not yet been approved (which is stated in the change log), but anyway I confirm that the changes are fully in line with the proposed changes.

**Review by ryanbnl — APPROVED** [review]

**Comment by mrkobk** [comment]
Hi,

as far as Im aware there is also new vaccines BionTech and Moderna Vaccines (BA.1) available soon-ish. Will this result in seperate/new valuesets for those or do they go under the current Comirnaty and Spikevax sets? Thanks

**Comment by dslmeinte** [comment]
Hi @mrkobk ,
_If_ it's decided by the eHN that it's necessary to be able to distinguish between variant-specific vaccines, then they will quite likely end up as separate entries in the appropriate value set. Yesterday, the v1.11 document was adopted during the eHN Coordinated Actions meeting, so that will also not be amended for variant-specific vaccines.

**Review by skounis — APPROVED** [review]

**Comment by dslmeinte** [comment]
Hi @kruzikh ,

Apologies: I totally didn't see you had already made a `release/2.9.0` branch for the value set update. I just merged a PR with the same content.

Now I just have to re-make a branch for the release 2.9.0 conforming to the release process (which I didn't follow precisely, or I'd seen your branch earlier). Would you mind if I deleted your 2.9.0 branch so I can hang the branch label on a commit that leads to `main`?

**Comment by kruzikh** [comment]
No problem, just remove it.

**Comment by dslmeinte** [comment]
> No problem, just remove it.

Thanks! Done, and re-created the branch from a commit leading to `main`.

**Pull request merged**
