### PR TITLE
Derive the Annex A value set

### PR DESCRIPTION
**Pull request by dslmeinte**

### CODE REVIEW

**Review by skounis — APPROVED** [review]
I corrected a small typo. 

I think if we build the `.json` with action and keep as the source of truth the `table.tsv` (not related to this PR)

**Comment by dslmeinte** [comment]
> I corrected a small typo.

Thanks! (Was result of copying from Pages.)

> I think if we build the `.json` with an action and keep as the source of truth the `table.tsv` (not related to this PR)

Could do that, but seeing that this process takes some manual labour and checking anyway, I'm not sure it's worth it already.

**Comment by ryanbnl** [comment]
I strongly prefer keeping the products here as JSON - it's easier to consume for most of the people who are using this repository and is consistent.

**Review by ryanbnl — APPROVED** [review]

**Comment by dslmeinte** [comment]
I'll have to re-create this PR to target the new `release/2.11.0` release branch (to stay compliant with `VERSIONING.md`).

**Pull request closed without merging**
